package com.hybris.caas.dto.order.enums;

public enum CreditCardStatus {
    AUTHORIZATION_APPROVED, AUTHORIZATION_INVALID, CHARGE_INVALID, CHARGE_DECLINED, CHARGE_APPROVED, REFUND_APPROVED, REFUND_DECLINED, REFUND_INVALID

}
